### ISSUE TITLE
Hardenise fails to detect SMTP TLS thus DANE

### ISSUE THREAD

**Issue by InputOutputZ** [hardenize/hardenize-public#74] opened 2021-12-15 19:52 UTC
Hi there,

I'm not sure why it's not working, despite I tested on https://internet.nl/mail/zakaria.website/635267/, https://dane.sys4.de/smtp/zakaria.website and everything seems to be perfectly ok but when I run test on hardenise https://www.hardenize.com/report/zakaria.website/1639493903, all that fails?

I looked at this issue https://github.com/hardenize/hardenize-public/issues/29, but I couldn't figure out if it's something to do with cache as well?

if a misconfiguration it's from my end any hints would be very much appreciated.

With thanks.

Zakaria.

**Comment by ivanr** [comment] 2021-12-15 21:22
I haven't yet had time to look into this, but virtually always the issue is that we're blocked by the SMTP servers, leading to the incomplete results. If you can add the IP addresses behind outbound.hardenize.com to an allow list, that may help. I'll try to look into it as soon as I can. Cheers.

**Comment by InputOutputZ** [comment] 2021-12-16 13:12
Hi Ivanr,

Thanks for your time anyhow and I've whitelisted the host IPs behind the relevant hostname.

It didnt make any difference yet checked it's kernel log and this is the output:-

```
Dec 16 13:00:35 localhost haproxy[1750]: 18.233.176.231:55354 [16/Dec/2021:13:00:35.938] httpd/3: SSL handshake failure
Dec 16 13:00:35 server haproxy: <134>Dec 16 13:00:35 haproxy[1750]: 18.233.176.231:55354 [16/Dec/2021:13:00:35.938] httpd/3: SSL handshake failure
Dec 16 13:00:35 localhost haproxy[1750]: 18.233.176.231:36125 [16/Dec/2021:13:00:35.963] httpd/3: SSL handshake failure
Dec 16 13:00:35 server haproxy: <134>Dec 16 13:00:35 haproxy[1750]: 18.233.176.231:36125 [16/Dec/2021:13:00:35.963] httpd/3: SSL handshake failure
Dec 16 13:00:48 localhost haproxy[1750]: 18.233.176.231:39876 [16/Dec/2021:13:00:48.960] httpd httpd/<NOSRV> 0/-1/-1/-1/0 301 236 - - LR-- 10/10/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:48 server haproxy: <134>Dec 16 13:00:48 haproxy[1750]: 18.233.176.231:39876 [16/Dec/2021:13:00:48.960] httpd httpd/<NOSRV> 0/-1/-1/-1/0 301 236 - - LR-- 10/10/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:49 localhost haproxy[1750]: 18.233.176.231:56950 [16/Dec/2021:13:00:49.397] httpd~ httpd/apache 0/0/1/0/2 200 93619 - - ---- 11/11/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:49 server haproxy: <134>Dec 16 13:00:49 haproxy[1750]: 18.233.176.231:56950 [16/Dec/2021:13:00:49.397] httpd~ httpd/apache 0/0/1/0/2 200 93619 - - ---- 11/11/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:49 localhost haproxy[1750]: 18.233.176.231:42897 [16/Dec/2021:13:00:49.792] httpd httpd/<NOSRV> 0/-1/-1/-1/0 301 240 - - LR-- 11/11/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:49 server haproxy: <134>Dec 16 13:00:49 haproxy[1750]: 18.233.176.231:42897 [16/Dec/2021:13:00:49.792] httpd httpd/<NOSRV> 0/-1/-1/-1/0 301 240 - - LR-- 11/11/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:50 localhost haproxy[1750]: 18.233.176.231:26272 [16/Dec/2021:13:00:50.238] httpd~ httpd/apache 0/0/0/1/1 301 1252 - - ---- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:50 server haproxy: <134>Dec 16 13:00:50 haproxy[1750]: 18.233.176.231:26272 [16/Dec/2021:13:00:50.238] httpd~ httpd/apache 0/0/0/1/1 301 1252 - - ---- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:51 localhost haproxy[1750]: 18.233.176.231:51947 [16/Dec/2021:13:00:51.420] httpd~ httpd/apache 0/0/1/1/2 200 93619 - - ---- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:51 server haproxy: <134>Dec 16 13:00:51 haproxy[1750]: 18.233.176.231:51947 [16/Dec/2021:13:00:51.420] httpd~ httpd/apache 0/0/1/1/2 200 93619 - - ---- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:52 localhost haproxy[1750]: 18.233.176.231:26515 [16/Dec/2021:13:00:52.063] httpd~ httpd/apache 0/0/1/0/1 301 1252 - - ---- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:52 server haproxy: <134>Dec 16 13:00:52 haproxy[1750]: 18.233.176.231:26515 [16/Dec/2021:13:00:52.063] httpd~ httpd/apache 0/0/1/0/1 301 1252 - - ---- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:53 localhost haproxy[1750]: 18.233.176.231:63008 [16/Dec/2021:13:00:53.736] httpd httpd/<NOSRV> 0/-1/-1/-1/0 301 236 - - LR-- 13/13/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:53 server haproxy: <134>Dec 16 13:00:53 haproxy[1750]: 18.233.176.231:63008 [16/Dec/2021:13:00:53.736] httpd httpd/<NOSRV> 0/-1/-1/-1/0 301 236 - - LR-- 13/13/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:54 server haproxy: <134>Dec 16 13:00:54 haproxy[1750]: 18.233.176.231:55763 [16/Dec/2021:13:00:54.177] httpd~ httpd/apache 0/0/1/1/5 200 334106 - - ---- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:54 localhost haproxy[1750]: 18.233.176.231:55763 [16/Dec/2021:13:00:54.177] httpd~ httpd/apache 0/0/1/1/5 200 334106 - - ---- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:55 localhost haproxy[1750]: 18.233.176.231:52779 [16/Dec/2021:13:00:55.221] httpd httpd/<NOSRV> 0/-1/-1/-1/0 301 240 - - LR-- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:55 server haproxy: <134>Dec 16 13:00:55 haproxy[1750]: 18.233.176.231:52779 [16/Dec/2021:13:00:55.221] httpd httpd/<NOSRV> 0/-1/-1/-1/0 301 240 - - LR-- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:55 localhost haproxy[1750]: 18.233.176.231:50254 [16/Dec/2021:13:00:55.669] httpd~ httpd/apache 0/0/1/0/1 301 1221 - - ---- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:55 server haproxy: <134>Dec 16 13:00:55 haproxy[1750]: 18.233.176.231:50254 [16/Dec/2021:13:00:55.669] httpd~ httpd/apache 0/0/1/0/1 301 1221 - - ---- 12/12/0/0/0 0/0 "GET / HTTP/1.1"
Dec 16 13:00:55 localhost haproxy[1750]: 18.233.176.231:22837 [16/Dec/2021:13:00:55.977] httpd/3: SSL handshake failure
Dec 16 13:00:55 server haproxy: <134>Dec 16 13:00:55 haproxy[1750]: 18.233.176.231:22837 [16/Dec/2021:13:00:55.977] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:17322 [16/Dec/2021:13:00:55.973] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:17322 [16/Dec/2021:13:00:55.973] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:47706 [16/Dec/2021:13:00:55.975] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:47706 [16/Dec/2021:13:00:55.975] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:22796 [16/Dec/2021:13:00:56.173] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:22796 [16/Dec/2021:13:00:56.173] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:40354 [16/Dec/2021:13:00:56.175] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:40354 [16/Dec/2021:13:00:56.175] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:57105 [16/Dec/2021:13:00:56.372] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:57105 [16/Dec/2021:13:00:56.372] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:49459 [16/Dec/2021:13:00:56.377] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:49459 [16/Dec/2021:13:00:56.377] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:34441 [16/Dec/2021:13:00:56.423] httpd~ httpd/<NOSRV> -1/-1/-1/-1/101 400 0 - - CR-- 12/12/0/0/0 0/0 "<BADREQ>"
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:34441 [16/Dec/2021:13:00:56.423] httpd~ httpd/<NOSRV> -1/-1/-1/-1/101 400 0 - - CR-- 12/12/0/0/0 0/0 "<BADREQ>"
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:23886 [16/Dec/2021:13:00:56.635] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:23886 [16/Dec/2021:13:00:56.635] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:37516 [16/Dec/2021:13:00:56.578] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:37516 [16/Dec/2021:13:00:56.578] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:38792 [16/Dec/2021:13:00:56.579] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:38792 [16/Dec/2021:13:00:56.579] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:18539 [16/Dec/2021:13:00:56.779] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:18539 [16/Dec/2021:13:00:56.779] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:30241 [16/Dec/2021:13:00:56.783] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:30241 [16/Dec/2021:13:00:56.783] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:53332 [16/Dec/2021:13:00:56.979] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:53332 [16/Dec/2021:13:00:56.979] httpd/3: SSL handshake failure
Dec 16 13:00:56 localhost haproxy[1750]: 18.233.176.231:37544 [16/Dec/2021:13:00:56.984] httpd/3: SSL handshake failure
Dec 16 13:00:56 server haproxy: <134>Dec 16 13:00:56 haproxy[1750]: 18.233.176.231:37544 [16/Dec/2021:13:00:56.984] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:60185 [16/Dec/2021:13:00:57.082] httpd~ httpd/<NOSRV> -1/-1/-1/-1/102 400 0 - - CR-- 15/15/0/0/0 0/0 "<BADREQ>"
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:60185 [16/Dec/2021:13:00:57.082] httpd~ httpd/<NOSRV> -1/-1/-1/-1/102 400 0 - - CR-- 15/15/0/0/0 0/0 "<BADREQ>"
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:51855 [16/Dec/2021:13:00:57.179] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:51855 [16/Dec/2021:13:00:57.179] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:39978 [16/Dec/2021:13:00:57.185] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:39978 [16/Dec/2021:13:00:57.185] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:56012 [16/Dec/2021:13:00:57.292] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:56012 [16/Dec/2021:13:00:57.292] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:15070 [16/Dec/2021:13:00:57.386] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:15070 [16/Dec/2021:13:00:57.386] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:51829 [16/Dec/2021:13:00:57.400] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:51829 [16/Dec/2021:13:00:57.400] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:17327 [16/Dec/2021:13:00:57.594] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:17327 [16/Dec/2021:13:00:57.594] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:51441 [16/Dec/2021:13:00:57.607] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:51441 [16/Dec/2021:13:00:57.607] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:55058 [16/Dec/2021:13:00:57.799] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:55058 [16/Dec/2021:13:00:57.799] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:21542 [16/Dec/2021:13:00:57.814] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:21542 [16/Dec/2021:13:00:57.814] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:19161 [16/Dec/2021:13:00:57.742] httpd~ httpd/<NOSRV> -1/-1/-1/-1/102 400 0 - - CR-- 12/12/0/0/0 0/0 "<BADREQ>"
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:19161 [16/Dec/2021:13:00:57.742] httpd~ httpd/<NOSRV> -1/-1/-1/-1/102 400 0 - - CR-- 12/12/0/0/0 0/0 "<BADREQ>"
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:50058 [16/Dec/2021:13:00:57.950] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:50058 [16/Dec/2021:13:00:57.950] httpd/3: SSL handshake failure
Dec 16 13:00:57 localhost haproxy[1750]: 18.233.176.231:38819 [16/Dec/2021:13:00:57.997] httpd/3: SSL handshake failure
Dec 16 13:00:57 server haproxy: <134>Dec 16 13:00:57 haproxy[1750]: 18.233.176.231:38819 [16/Dec/2021:13:00:57.997] httpd/3: SSL handshake failure
Dec 16 13:00:58 localhost haproxy[1750]: 18.233.176.231:30374 [16/Dec/2021:13:00:58.015] httpd/3: SSL handshake failure
Dec 16 13:00:58 server haproxy: <134>Dec 16 13:00:58 haproxy[1750]: 18.233.176.231:30374 [16/Dec/2021:13:00:58.015] httpd/3: SSL handshake failure
Dec 16 13:00:58 localhost haproxy[1750]: 18.233.176.231:46567 [16/Dec/2021:13:00:58.194] httpd/3: SSL handshake failure
Dec 16 13:00:58 server haproxy: <134>Dec 16 13:00:58 haproxy[1750]: 18.233.176.231:46567 [16/Dec/2021:13:00:58.194] httpd/3: SSL handshake failure
Dec 16 13:00:58 localhost haproxy[1750]: 18.233.176.231:49938 [16/Dec/2021:13:00:58.214] httpd/3: SSL handshake failure
Dec 16 13:00:58 server haproxy: <134>Dec 16 13:00:58 haproxy[1750]: 18.233.176.231:49938 [16/Dec/2021:13:00:58.214] httpd/3: SSL handshake failure
Dec 16 13:00:58 localhost haproxy[1750]: 18.233.176.231:56511 [16/Dec/2021:13:00:58.389] httpd~ httpd/<NOSRV> -1/-1/-1/-1/99 400 0 - - CR-- 16/16/0/0/0 0/0 "<BADREQ>"
Dec 16 13:00:58 server haproxy: <134>Dec 16 13:00:58 haproxy[1750]: 18.233.176.231:56511 [16/Dec/2021:13:00:58.389] httpd~ httpd/<NOSRV> -1/-1/-1/-1/99 400 0 - - CR-- 16/16/0/0/0 0/0 "<BADREQ>"
Dec 16 13:00:58 localhost haproxy[1750]: 18.233.176.231:30478 [16/Dec/2021:13:00:58.391] httpd/3: SSL handshake failure
Dec 16 13:00:58 server haproxy: <134>Dec 16 13:00:58 haproxy[1750]: 18.233.176.231:30478 [16/Dec/2021:13:00:58.391] httpd/3: SSL handshake failure
Dec 16 13:00:58 localhost haproxy[1750]: 18.233.176.231:34412 [16/Dec/2021:13:00:58.413] httpd/3: SSL handshake failure
Dec 16 13:00:58 server haproxy: <134>Dec 16 13:00:58 haproxy[1750]: 18.233.176.231:34412 [16/Dec/2021:13:00:58.413] httpd/3: SSL handshake failure
Dec 16 13:00:58 localhost haproxy[1750]: 18.233.176.231:26209 [16/Dec/2021:13:00:58.591] httpd/3: SSL handshake failure
Dec 16 13:00:58 server haproxy: <134>Dec 16 13:00:58 haproxy[1750]: 18.233.176.231:26209 [16/Dec/2021:13:00:58.591] httpd/3: SSL handshake failure
Dec 16 13:00:58 localhost haproxy[1750]: 18.233.176.231:49472 [16/Dec/2021:13:00:58.615] httpd/3: SSL handshake failure
Dec 16 13:00:58 server haproxy: <134>Dec 16 13:00:58 haproxy[1750]: 18.233.176.231:49472 [16/Dec/2021:13:00:58.615] httpd/3: SSL handshake failure
Dec 16 13:00:58 localhost haproxy[1750]: 18.233.176.231:42414 [16/Dec/2021:13:00:58.840] httpd~ httpd/apache 0/0/1/0/1 200 8421 - - ---- 16/16/0/0/0 0/0 "GET /apple-icon-144x144.png HTTP/1.1"
Dec 16 13:00:58 server haproxy: <134>Dec 16 13:00:58 haproxy[1750]: 18.233.176.231:42414 [16/Dec/2021:13:00:58.840] httpd~ httpd/apache 0/0/1/0/1 200 8421 - - ---- 16/16/0/0/0 0/0 "GET /apple-icon-144x144.png HTTP/1.1"
Dec 16 13:00:58 localhost haproxy[1750]: 18.233.176.231:40584 [16/Dec/2021:13:00:58.800] httpd/3: SSL handshake failure
Dec 16 13:00:58 server haproxy: <134>Dec 16 13:00:58 haproxy[1750]: 18.233.176.231:40584 [16/Dec/2021:13:00:58.800] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:46378 [16/Dec/2021:13:00:59.001] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:46378 [16/Dec/2021:13:00:59.001] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:58728 [16/Dec/2021:13:00:58.820] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:58728 [16/Dec/2021:13:00:58.820] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:46083 [16/Dec/2021:13:00:59.117] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:46083 [16/Dec/2021:13:00:59.117] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:46960 [16/Dec/2021:13:00:59.223] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:46960 [16/Dec/2021:13:00:59.223] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:46545 [16/Dec/2021:13:00:59.336] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:46545 [16/Dec/2021:13:00:59.336] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:51592 [16/Dec/2021:13:00:59.421] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:51592 [16/Dec/2021:13:00:59.421] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:29366 [16/Dec/2021:13:00:59.537] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:29366 [16/Dec/2021:13:00:59.537] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:20410 [16/Dec/2021:13:00:59.618] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:20410 [16/Dec/2021:13:00:59.618] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:54152 [16/Dec/2021:13:00:59.737] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:54152 [16/Dec/2021:13:00:59.737] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:41124 [16/Dec/2021:13:00:59.815] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:41124 [16/Dec/2021:13:00:59.815] httpd/3: SSL handshake failure
Dec 16 13:00:59 localhost haproxy[1750]: 18.233.176.231:26099 [16/Dec/2021:13:00:59.940] httpd/3: SSL handshake failure
Dec 16 13:00:59 server haproxy: <134>Dec 16 13:00:59 haproxy[1750]: 18.233.176.231:26099 [16/Dec/2021:13:00:59.940] httpd/3: SSL handshake failure
Dec 16 13:01:00 localhost haproxy[1750]: 18.233.176.231:42459 [16/Dec/2021:13:01:00.011] httpd/3: SSL handshake failure
Dec 16 13:01:00 server haproxy: <134>Dec 16 13:01:00 haproxy[1750]: 18.233.176.231:42459 [16/Dec/2021:13:01:00.011] httpd/3: SSL handshake failure
Dec 16 13:01:00 localhost haproxy[1750]: 18.233.176.231:54985 [16/Dec/2021:13:01:00.142] httpd/3: SSL handshake failure
Dec 16 13:01:00 server haproxy: <134>Dec 16 13:01:00 haproxy[1750]: 18.233.176.231:54985 [16/Dec/2021:13:01:00.142] httpd/3: SSL handshake failure
Dec 16 13:01:00 localhost haproxy[1750]: 18.233.176.231:42818 [16/Dec/2021:13:01:00.211] httpd/3: SSL handshake failure
Dec 16 13:01:00 server haproxy: <134>Dec 16 13:01:00 haproxy[1750]: 18.233.176.231:42818 [16/Dec/2021:13:01:00.211] httpd/3: SSL handshake failure
Dec 16 13:01:00 localhost haproxy[1750]: 18.233.176.231:56817 [16/Dec/2021:13:01:00.344] httpd/3: SSL handshake failure
Dec 16 13:01:00 server haproxy: <134>Dec 16 13:01:00 haproxy[1750]: 18.233.176.231:56817 [16/Dec/2021:13:01:00.344] httpd/3: SSL handshake failure
Dec 16 13:01:00 localhost haproxy[1750]: 18.233.176.231:34645 [16/Dec/2021:13:01:00.412] httpd/3: SSL handshake failure
Dec 16 13:01:00 server haproxy: <134>Dec 16 13:01:00 haproxy[1750]: 18.233.176.231:34645 [16/Dec/2021:13:01:00.412] httpd/3: SSL handshake failure
Dec 16 13:01:00 localhost haproxy[1750]: 18.233.176.231:52827 [16/Dec/2021:13:01:00.543] httpd/3: SSL handshake failure
Dec 16 13:01:00 server haproxy: <134>Dec 16 13:01:00 haproxy[1750]: 18.233.176.231:52827 [16/Dec/2021:13:01:00.543] httpd/3: SSL handshake failure
Dec 16 13:01:00 localhost haproxy[1750]: 18.233.176.231:27534 [16/Dec/2021:13:01:00.612] httpd/3: SSL handshake failure
Dec 16 13:01:00 server haproxy: <134>Dec 16 13:01:00 haproxy[1750]: 18.233.176.231:27534 [16/Dec/2021:13:01:00.612] httpd/3: SSL handshake failure
Dec 16 13:01:00 localhost haproxy[1750]: 18.233.176.231:38452 [16/Dec/2021:13:01:00.811] httpd/3: SSL handshake failure
Dec 16 13:01:00 server haproxy: <134>Dec 16 13:01:00 haproxy[1750]: 18.233.176.231:38452 [16/Dec/2021:13:01:00.811] httpd/3: SSL handshake failure
Dec 16 13:01:00 localhost haproxy[1750]: 18.233.176.231:46939 [16/Dec/2021:13:01:00.742] httpd/3: SSL handshake failure
Dec 16 13:01:00 server haproxy: <134>Dec 16 13:01:00 haproxy[1750]: 18.233.176.231:46939 [16/Dec/2021:13:01:00.742] httpd/3: SSL handshake failure
Dec 16 13:01:00 localhost haproxy[1750]: 18.233.176.231:21938 [16/Dec/2021:13:01:00.943] httpd/3: SSL handshake failure
Dec 16 13:01:00 server haproxy: <134>Dec 16 13:01:00 haproxy[1750]: 18.233.176.231:21938 [16/Dec/2021:13:01:00.943] httpd/3: SSL handshake failure.
```

Are there any settings you would usually recommend for HAProxy, HTTPD, Dovcote, EXIM? note the EXIM mail server its not served from behind HAProxy, but from its own port directly? Also, note I've TLS 1.2 and 1.3 only it's being enabled.

With thanks.

Zakaria.

**Comment by ivanr** [comment] 2021-12-16 13:40
Thanks for that. I may have sent you up the wrong path. I started to troubleshoot in the meantime and I think this might be a bug on our end. The issue is that we're not sending the correct ALPN extension for SMTP traffic. I am seeing no_application_protocol alerts in the network captures.

**Comment by ivanr** [comment] 2021-12-16 14:25
I have fixed the problem; here's the report in our staging environment: https://staging.hardenize.net/report/zakaria.website/1639664626#email_dane It will be in production in due course.

Many thanks for reporting this problem!

**Closed as completed by ivanr** 2021-12-16 14:25 UTC

**Comment by InputOutputZ** [comment] 2021-12-16 15:31
I thought this might help, note, I use pre-release master from source OpenSSL as well as EXIM installation, and their developers have incorporated new and deprecated old methods, and things seems to have been changed a bit, please refer to EXIM repo recent commits about OpenSSL 3 and OpenSSL 3.1.0-dev release. 

Anyhow, thanks for your quick fix, and have a lovely evening.

Zakaria.
