### ISSUE TITLE
Scanning fail for Hosts offering TLS1.3 only

### ISSUE THREAD

**Issue by andreasschulze** [hardenize/hardenize-public#61] opened 2019-05-29 10:02 UTC
see https://www.hardenize.com/report/tls13only.andreasschulze.de/1559123989#www_http

SSLLabs and testssh.sh have similiar problems

**Comment by ivanr** [comment] 2019-05-29 11:53
The root cause is the fact that Java 8, which we rely on, doesn't support TLS 1.3. We're looking at upgrading our systems to Java 12, which does support TLS 1.3, but it's a significant change (in terms of testing) and most systems will continue to support TLS 1.2 for a period of time.

BTW, this is a duplicate of our first issue :) https://github.com/hardenize/hardenize-public/issues/1

**Closed as completed** 2019-05-29 11:53 UTC
Labels: bug
